logging:
  level:
    org.springframework.security: debug
    org.springframework.jdbc.core: trace
spring:
  messages:
    basename: messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    encoding: UTF-8
  profiles:
    active: prod
uwjx:
  jwt:
    accessTokenExpireTime: 999999
    refreshTokenExpireTime: 89999999999999